-- [nfnl] init.fnl
require("core.vars")
require("core.opts")
require("core.fts")
require("lz")
require("core.aucmds")
require("core.hls")
require("core.maps")
require("core.ts")
return require("core.lsp")
